/**
 * What a renderer produces: one named file, ready to download.
 *
 * Renderers are pure functions of the model. None of them knows a scheme
 * exists — the warped model is simply the model, and the statement reports it
 * faithfully. That is what makes a planted overcharge coherent instead of
 * cartoonish: the landlord's own paperwork agrees with itself everywhere except
 * the one seam the scheme broke.
 */

export type ArtifactKind = "xlsx" | "html" | "json" | "text";

export interface Artifact {
  /** The filename as it appears in the package, without any folder. */
  filename: string;
  kind: ArtifactKind;
  /** What this document is, for the download list and the preview tabs. */
  title: string;
  /** The reconciliation year it belongs to, or null for documents spanning the term. */
  year: number | null;
  bytes: Uint8Array | string;
}

/** The small print at the foot of every rendered page and sheet. */
export const SYNTHETIC_NOTICE =
  "Synthetic document generated by Recon Foundry for training. Every party, property and figure is fictional.";
