/**
 * What a renderer produces: one named file, ready to download.
 *
 * Renderers are pure functions of the model. None of them knows a scheme
 * exists — the warped model is simply the model, and the statement reports it
 * faithfully. That is what makes a planted overcharge coherent instead of
 * cartoonish: the landlord's own paperwork agrees with itself everywhere except
 * the one seam the scheme broke.
 */

import type { Branding } from "../model/types.ts";

export type ArtifactKind = "xlsx" | "html" | "json" | "text";

export interface Artifact {
  /** The filename as it appears in the package, without any folder. */
  filename: string;
  kind: ArtifactKind;
  /** What this document is, for the download list and the preview tabs. */
  title: string;
  /** The reconciliation year it belongs to, or null for documents spanning the term. */
  year: number | null;
  bytes: Uint8Array | string;
}

/** The small print at the foot of every rendered page and sheet. */
export const SYNTHETIC_NOTICE =
  "Synthetic document generated by Recon Foundry for training. Every party, property and figure is fictional.";

/**
 * The names this engine answers to, and the small print they compose.
 *
 * A forged package says who forged it, in the notice at the foot of every page,
 * in the workbook's file properties, and in the note at the root of the ZIP.
 * Those sentences were written for a training exercise handed out by this app,
 * which is the only place a package went until another app in the family
 * started forging them to show a prospective client what a landlord's paperwork
 * looks like. A package that names an app the reader has never heard of is a
 * package that reads like it was borrowed from somewhere.
 *
 * So the names are a parameter, and `Branding` on `ScenarioConfig` is where a
 * caller sets them. **Absent, every one of these returns exactly the string the
 * constant below always held**, which is what keeps the pinned fixtures pinned;
 * `tests/branding.test.ts` holds both halves of that.
 *
 * `notice` is overridable as a whole rather than composed, because the stock
 * sentence says the document was generated "for training" — true of this app's
 * own packages and wrong on a page that is not teaching anyone.
 */
export const FORGE_NAME = "Recon Foundry";
export const SCANNER_NAME = "Red-Flag Scanner";

export function forgeName(b?: Branding): string {
  return b?.forge ?? FORGE_NAME;
}

export function scannerName(b?: Branding): string {
  return b?.scanner ?? SCANNER_NAME;
}

/** The small print, composed from the forge's name unless it is given outright. */
export function syntheticNotice(b?: Branding): string {
  if (b?.notice !== undefined) return b.notice;
  return `Synthetic document generated by ${forgeName(b)} for training. Every party, property and figure is fictional.`;
}

/**
 * What the workbook's file properties say made it.
 *
 * `xlsx/writer.ts` holds the un-branded string as its own constant rather than
 * importing this — a low-level writer that reached up into the renderers would
 * be the wrong way round — so the two agree by a test rather than by
 * construction. `tests/branding.test.ts` reads an un-branded workbook back and
 * requires its creator to be exactly what this returns with no argument.
 */
export function creatorName(b?: Branding): string {
  return `${forgeName(b)} — synthetic training data`;
}
